In [1]:
import pandas as pd

In [5]:
data = pd.read_csv('titanic.csv')
data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
data.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,False,False,False,False,False,False,False,False,False,False,True,False
1,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,True,False
3,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,True,False
...,...,...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False,True,False
887,False,False,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False,True,False
889,False,False,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False,True,False

In [17]:
new_data = data.dropna()

In [19]:
new_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S

In [21]:
new_data.shape

(183, 12)

In [23]:
new_data.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

C:\Users\sdara\AppData\Local\Temp\ipykernel_19284\2772674206.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis='columns',inplace=True)

In [25]:
new_data.head()

    Survived  Pclass     Sex   Age     Fare
1          1       1  female  38.0  71.2833
3          1       1  female  35.0  53.1000
6          0       1    male  54.0  51.8625
10         1       3  female   4.0  16.7000
11         1       1  female  58.0  26.5500

In [ ]:
from sklearn.preprocessing import LabelEncoder

le_sex =  LabelEncoder()

In [42]:
new_data['sex_new'] = le_sex.fit_transform(new_data['Sex'])

C:\Users\sdara\AppData\Local\Temp\ipykernel_19284\284720222.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_data['sex_new'] = le_sex.fit_transform(new_data['Sex'])

In [46]:
last_data = new_data.drop(['Sex'],axis='columns')
last_data.head()

    Survived  Pclass   Age     Fare  sex_new
1          1       1  38.0  71.2833        0
3          1       1  35.0  53.1000        0
6          0       1  54.0  51.8625        1
10         1       3   4.0  16.7000        0
11         1       1  58.0  26.5500        0

In [50]:
from sklearn import tree

model = tree.DecisionTreeClassifier()

In [52]:
from sklearn.model_selection import train_test_split

x = last_data.iloc[:,1:5]
y = last_data.iloc[:,0]
x_test , x_train , y_test , y_train = train_test_split(x,y,test_size=0.2,random_state=10)

In [54]:
x_test.shape

(146, 4)

In [56]:
x_train.shape

(37, 4)

In [58]:
x.shape

(183, 4)

In [65]:
model.fit(x_train,y_train)

DecisionTreeClassifier()

In [67]:
pred = model.predict(x_test)

In [85]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(pred,y_test)
cm

array([[27, 16],
       [23, 80]], dtype=int64)

In [87]:
model.score(x_test,y_test)

0.7328767123287672